### ISSUE TITLE
Tests fail or pass depending on how `runtests.jl` is executed

### ISSUE THREAD

**Issue by hkraemer** [JuliaDynamics/TreeEmbedding.jl#10]
FYI, @Datseris and @maximilian-gelbrecht : https://discourse.julialang.org/t/unable-to-reproduce-unit-test-outcomes-from-package-managers-clean-environment/79772

**Comment by Datseris** [comment]
Can you point me which test in the source code is the failing one? Maybe that will help me identify the problem...

**Comment by hkraemer** [comment]
See the last commit; I commented everything out, but the not-working test. When running it via `] test TreeEmbedding` I'll get as delay values `[0,1,5]`. So does @maximilian-gelbrecht on his machine. 

I also have to mention that the other tests were also quite brittle and I had to adjust them. Therefore I conclude that it is really the environment-thingy, which I need to figure out in order to write robust tests...

**Comment by hkraemer** [comment]
After hours of diggin into the code I found the error, eventually. - And it does not make me happy at all! Instead of 
```julia
costs = zeros(T, NN, D)
@inbounds for (i,v) in enumerate(ns)
   costs[i,:] = (Vector(prediction[i]) .- Vector(Y[v+Tw])).^2
end
```
this here 
```julia
costs = abs2.(Matrix(prediction) - Matrix(Y[ns.+Tw]))
```
works perfectly on all machines and runners. Why is this? Anyway, I'll accept this and close the issue.
